	Proc Sort Data = Work.X_01(Keep=Hierarchy Data_Element) 
		Out = Work.X_01_Nodup NoDupKey;
		By Hierarchy Data_Element;
	Run;

	Proc Sort Data = Work.X_01_nodup(Keep=Hierarchy Data_Element) 
		Out = Work.X_02_nodup;
		By Data_Element;
	Run;

Data Work.X_03_nodup;
	Set Work.X_02_nodup;
		*--- Amounts ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-Amount' Then Data_Element = 'CreditInterestAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-TradingHistoryEligibility-Amount' Then Data_Element = 'EligibilityAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Amount' Then Data_Element = 'FeatureBenefitEligAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Amount' Then Data_Element = 'FeatureBenefitGrpItemAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Amount' Then Data_Element = 'FeatureBenefitGrpItemEligAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Amount' Then Data_Element = 'FeatureBenefitItemAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Amount' Then Data_Element = 'FeatureBenefitItemEligAmount';
		*--- ApplicationFrequency ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-TierBand-ApplicationFrequency' Then Data_Element = 'TierBandAppFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-ApplicationFrequency' Then Data_Element = 'FeatureBenefitGrpAppFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-ApplicationFrequency' Then Data_Element = 'FeeChargeDetailAppFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-ApplicationFrequency' Then Data_Element = 'OverdraftFeeChargeDetailAppFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-ApplicationFrequency' Then Data_Element = 'OverdraftTierbandAppFreq';

		*--- CalculationFrequency ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-TierBand-CalculationFrequency' Then Data_Element = 'TierBandCalcFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-CalculationFrequency' Then Data_Element = 'FeatureBenefitGrpCalcFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-CalculationFrequency' Then Data_Element = 'FeeChargeDetailCalcFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-CalculationFrequency' Then Data_Element = 'OverdraftFeeChargeDetailCalcFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-CalculationFrequency' Then Data_Element = 'OverdraftTierbandCalcFreq';

		*--- CappingPeriod ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-CappingPeriod' Then Data_Element = 'FeeChargeCapPeriod';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeCap-CappingPeriod' Then Data_Element = 'OverdraftFeeChargeCapPeriod';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-CappingPeriod' Then Data_Element = 'OverdraftTierbandCapPeriod';
		*--- Code ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OfficerEligibility-OtherOfficerType-Code' Then Data_Element = 'EligOtherOfficerTypeCode';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-OtherType-Code' Then Data_Element = 'FeatureBenefitItemOtherTypeCode';
		*--- Description ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-Description' Then Data_Element = 'CreditIntEligDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-OtherType-Description' Then Data_Element = 'CreditIntEligOtherTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-IndustryEligibility-OtherSICCode-Description' Then Data_Element = 'OtherSICCodeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-LegalStructureEligibility-OtherLegalStructure-Description' Then Data_Element = 'OtherLegalStructureDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OfficerEligibility-OtherOfficerType-Description' Then Data_Element = 'OtherOfficerTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-Description' Then Data_Element = 'OtherEligibilityDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-OtherType-Description' Then Data_Element = 'OtherEligOtherTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-Card-OtherType-Description' Then Data_Element = 'CardOtherTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Description' Then Data_Element = 'FeatureBenefitGrpEligDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-OtherType-Description' Then Data_Element = 'FeatureBenItemGrpOtherTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-OtherType-Description' Then Data_Element = 'FeatureBenGrpOtherTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Description' Then Data_Element = 'FeatureBenItemEligDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType-Description' Then Data_Element = 'FeatureBenItemOtherTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-OtherFeeType-Description' Then Data_Element = 'FeeChargeCapOtherFeeTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType-Description' Then Data_Element = 'FeeChargeDetailOtherFeeTypeDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherApplicationFrequency-Description' Then Data_Element = 'OtherAppFreqDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherCalculationFrequency-Description' Then Data_Element = 'OtherCalcFreqDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherApplicationFrequency-Description' Then Data_Element = 'OverdraftFeeChargeAppFreqDesc';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherCalculationFrequency-Description' Then Data_Element = 'OverdraftFeeChargeCalcFreqDesc';
		*--- FeatureBenefitEligibility ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenefitGrpElig';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenefitGrpItemElig';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenefitElig';
		*--- FeatureBenefitItem ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem' Then Data_Element = 'FeatureBenefitGrpItem';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem' Then Data_Element = 'FeatureBenefitItem';
		*--- FeeAmount ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-FeeAmount' Then Data_Element = 'OtherFeesChargesAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeAmount' Then Data_Element = 'OverdraftFeesChargesAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeAmount' Then Data_Element = 'OverdraftTierBandAmount';
		*--- FeeCapAmount ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-FeeCapAmount' Then Data_Element = 'OtherFeesChargesFeeCapAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeCapAmount' Then Data_Element = 'OverdraftTierBandSetFeeCapAmount';
		*--- FeeCapOccurrence ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeCapAmount' Then Data_Element = 'OverdraftFeeCapAmount';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeCapOccurrence' Then Data_Element = 'OverdraftFeeCapOccurrence';
		*--- FeeCategory ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-FeeCategory' Then Data_Element = 'FeeChargeDetailFeeCategory';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType-FeeCategory' Then Data_Element = 'OtherFeeTypeFeeCategory';
		*--- FeeRate ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-FeeRate' Then Data_Element = 'FeeChargeDetailFeeRate';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeRate' Then Data_Element = 'OverdraftFeesChargesFeeRate';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeRate' Then Data_Element = 'OverdraftTierBandFeeRate';
		*--- FeeRateType ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-FeeRateType' Then Data_Element = 'FeeChargeDetailFeeRateType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeRateType' Then Data_Element = 'OverdraftFeesChargesFeeRateType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeRateType' Then Data_Element = 'OverdraftTierBandFeeRateType';
		*--- FeeType ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-FeeType' Then Data_Element = 'FeeChargeCapFeeType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-FeeType' Then Data_Element = 'FeeChargeDetailFeeType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeType' Then Data_Element = 'OverdraftFeeChargeCapFeeType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeType' Then Data_Element = 'OverdraftFeeChargeDetailFeeType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeType' Then Data_Element = 'OverdraftTierbandCapFeeType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-FeeType' Then Data_Element = 'OverdraftTierbandFeeType';
		*--- FeeType1 ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-FeeType-FeeType1' Then Data_Element = 'FeeChargeCapFeeType1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeType-FeeType1' Then Data_Element = 'OverdraftFeesChargesFeeType1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeType-FeeType1' Then Data_Element = 'OverdraftTierBandFeeType1';
		*--- FeeType2 ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-FeeType-FeeType2' Then Data_Element = 'FeeChargeCapFeeType2';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeType-FeeType2' Then Data_Element = 'OverdraftFeeChargeCapFeeType2';
		*--- FeeType3 ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-FeeType-FeeType3' Then Data_Element = 'FeeChargeCapFeeType3';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-FeeType-FeeType3' Then Data_Element = 'OverdraftFeeChargeCapFeeType3';
		*--- Identification ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-TierBand-Identification' Then Data_Element = 'CreditIntIndentification';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Identification' Then Data_Element = 'FeatureBenGrpItemIndentification';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Identification' Then Data_Element = 'FeatureBenItemIndentification';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Identification' Then Data_Element = 'BCAMarketingStateIdentification';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-Identification' Then Data_Element = 'OverdraftIdentification';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-Identification' Then Data_Element = 'OverdraftTierBandIdentification';
		If Hierarchy = 'data-Brand-BCA-Identification' Then Data_Element = 'BCAIdentification';
		*--- Indicator ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-Indicator' Then Data_Element = 'CreditIntEligIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-Indicator' Then Data_Element = 'OtherEligIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-TradingHistoryEligibility-Indicator' Then Data_Element = 'TradingHistEligibIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenGrpEligIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenItemEligIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Indicator' Then Data_Element = 'FeatureBenGrpItemIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenEligIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Indicator' Then Data_Element = 'FeatureBenItemIndicator';
		*--- MinMaxType ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-TradingHistoryEligibility-MinMaxType' Then Data_Element = 'TradingHistEligibMinMaxType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-MinMaxType' Then Data_Element = 'FeeChargeCapMinMaxType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeCap-MinMaxType' Then Data_Element = 'OverdraftFeeChargeCapMinMaxType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap-MinMaxType' Then Data_Element = 'OverdraftTierbandCapMinMaxType';
		*--- Name ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-Name' Then Data_Element = 'CreditIntEligName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-OtherType-Name' Then Data_Element = 'CreditIntEligOtherTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-IndustryEligibility-OtherSICCode-Name' Then Data_Element = 'OtherSICCodeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-LegalStructureEligibility-OtherLegalStructure-Name' Then Data_Element = 'OtherLegalStructureName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OfficerEligibility-OtherOfficerType-Name' Then Data_Element = 'OfficerEligOtherOfficerTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-Name' Then Data_Element = 'OtherEligName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-OtherType-Name' Then Data_Element = 'OtherEligOtherTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-Card-OtherType-Name' Then Data_Element = 'FeaturesBenCardOtherTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenGrpEligName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenGrpItemEligName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Name' Then Data_Element = 'FeatureBenGrpItemName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-OtherType-Name' Then Data_Element = 'FeatureBenGrpItemOtherTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Name' Then Data_Element = 'FeatureBenefitGrpName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-OtherType-Name' Then Data_Element = 'FeatureBenGrpOtherTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenItemEligName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Name' Then Data_Element = 'FeatureBenItemName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType-Name' Then Data_Element = 'FeatureBenOtherTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-OtherFeeType-Name' Then Data_Element = 'FeeChargeCapOtherFeeTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType-Name' Then Data_Element = 'FeeChargeDetailOtherFeeTypeName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherApplicationFrequency-Name' Then Data_Element = 'OverdraftFeeOtherAppFreqName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherCalculationFrequency-Name' Then Data_Element = 'OverdraftFeeOtherCalcFreqName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherApplicationFrequency-Name' Then Data_Element = 'OverdraftTierbandAppFreqName';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherCalculationFrequency-Name' Then Data_Element = 'OverdraftTierbandCalcFreqName';
		If Hierarchy = 'data-Brand-BCA-Name' Then Data_Element = 'BrandBCAName';
		*--- Negotiator ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-NegotiableIndicator' Then Data_Element = 'FeeChargeNegotiableIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-NegotiableIndicator' Then Data_Element = 'OverdraftTierbandNegleIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-NegotiableIndicator' Then Data_Element = 'OverdraftFeeChargeNegIndicator';
		*--- Notes ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CoreProduct-Notes' Then Data_Element = 'CoreProductNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-Notes' Then Data_Element = 'CreditIntTierBandSetNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-TierBand-Notes' Then Data_Element = 'CreditIntTierBandNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-AgeEligibility-Notes' Then Data_Element = 'AgeEligibilityNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-CreditCheckEligibility-Notes' Then Data_Element = 'CreditCheckEligNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-IDEligibility-Notes' Then Data_Element = 'IDEligNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-LegalStructureEligibility-Notes' Then Data_Element = 'LegalStructureEligNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OfficerEligibility-Notes' Then Data_Element = 'OfficerEligNotes';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-Notes' Then Data_Element = 'OtherEligNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-ResidencyEligibility-Notes' Then Data_Element = 'ResidencyEligNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-TradingHistoryEligibility-Notes' Then Data_Element = 'TradingHistEligNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-Card-Notes' Then Data_Element = 'FeaturesBenCardNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Notes' Then Data_Element = 'FeatureBenGrpEligNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Notes' Then Data_Element = 'FeatureBenGrpNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Notes' Then Data_Element = 'FeatureBenEligNotes';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Notes' Then Data_Element = 'FeatureBenItemNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-MobileWallet-Notes' Then Data_Element = 'MobileWalletNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Notes' Then Data_Element = 'BCAMarketingStateNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-Notes' Then Data_Element = 'FeeChargeCapNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-Notes' Then Data_Element = 'FeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-Notes' Then Data_Element = 'OverdraftNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-Notes' Then Data_Element = 'OverdraftTierBandSetNotes';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-Notes' Then Data_Element = 'OverdraftFeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-Notes' Then Data_Element = 'OverdraftTierBandNotes';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-Notes' Then Data_Element = 'OverdraftTierbandNotes';
		*--- Notes1 ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CoreProduct-Notes-Notes1' Then Data_Element = 'CoreProductNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-Notes-Notes1' Then Data_Element = 'TierBandSetNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-TierBand-Notes-Notes1' Then Data_Element = 'TierBandNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-AgeEligibility-Notes-Notes1' Then Data_Element = 'AgeEligibilityNotes1';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-CreditCheckEligibility-Notes-Notes1' Then Data_Element = 'CreditCheckEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-IDEligibility-Notes-Notes1' Then Data_Element = 'IDEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-LegalStructureEligibility-Notes-Notes1' Then Data_Element = 'LegalStructureEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OfficerEligibility-Notes-Notes1' Then Data_Element = 'OfficerEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-Notes-Notes1' Then Data_Element = 'OtherEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-ResidencyEligibility-Notes-Notes1' Then Data_Element = 'ResidencyEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-TradingHistoryEligibility-Notes-Notes1' Then Data_Element = 'TradingHistEligNotes1';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-Card-Notes-Notes1' Then Data_Element = 'FeaturesBenCardNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Notes-Notes1' Then Data_Element = 'FeatureBenItemEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Notes-Notes1' Then Data_Element = 'FeatureBenGrpNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Notes-Notes1' Then Data_Element = 'FeatureBenEligNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Notes-Notes1' Then Data_Element = 'FeatureBenItemNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-MobileWallet-Notes-Notes1' Then Data_Element = 'MobileWalletNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Notes-Notes1' Then Data_Element = 'BCAMarketingStateNotes1';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-Notes-Notes1' Then Data_Element = 'FeeChargeDetailNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-Notes-Notes1' Then Data_Element = 'OverdraftTierBandSetNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-Notes-Notes1' Then Data_Element = 'OverdraftFeeChargeNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-Notes-Notes1' Then Data_Element = 'OverdraftTierBandNotes1';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-Notes-Notes1' Then Data_Element = 'OverdraftTierbandNotes1';
		*--- Notes2 ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Notes-Notes2' Then Data_Element = 'BCAMarketingStateNotes2';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-Notes-Notes2' Then Data_Element = 'FeeChargeDetailNotes2';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-Notes-Notes2' Then Data_Element = 'OverdraftTierBandSetNotes2';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-Notes-Notes2' Then Data_Element = 'OverdraftFeeChargeDetailNotes2';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-Notes-Notes2' Then Data_Element = 'OverdraftTierbandNotes2';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Notes-Notes3' Then Data_Element = 'BCAMarketingStateNotes3';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-Notes-Notes3' Then Data_Element = 'OtherFeesChargesDetailNotes3';
		*--- OtherApplicationFrequency ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherApplicationFrequency' Then Data_Element = 'OverdraftFeesChargesOtherAppFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherApplicationFrequency' Then Data_Element = 'OverdraftTierBandOtherAppFreq';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-OtherCalculationFrequency' Then Data_Element = 'OverdraftFeeChargeOtherCalcFreq';
		If Hierarchy = 'OtherCalculationFrequency' Then Data_Element = 'OtherCalcFreq';
		*--- OtherFeeType ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeCap-OtherFeeType' Then Data_Element = 'FeeChargeCapOtherFeeType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType' Then Data_Element = 'FeeChargeDetailOtherFeeType';
		*--- OtherType ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-OtherType' Then Data_Element = 'CreditIntEligOtherType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-OtherType' Then Data_Element = 'OtherEligOtherType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-Card-OtherType' Then Data_Element = 'FeaturesBenCardOtherType';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-OtherType' Then Data_Element = 'FeatureBenefitGrpItemOtherType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-OtherType' Then Data_Element = 'FeatureBenGrpOtherType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType' Then Data_Element = 'FeatureBenItemOtherType';
		*--- OverdraftControlIndicator ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail-OverdraftControlIndicator' Then Data_Element = 'OverdraftFeesChargesIndicator';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail-OverdraftControlIndicator' Then Data_Element = 'OverdraftTierbandIndicator';
		*--- OverdraftFeeChargeCap ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeCap' Then Data_Element = 'OverdraftFeesChargesFeeChargeCap';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeCap' Then Data_Element = 'OverdraftTierBandFeeChargeCap';
		*--- OverdraftFeeChargeDetail ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges-OverdraftFeeChargeDetail' Then Data_Element = 'OverdraftFeesChargesDetail';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges-OverdraftFeeChargeDetail' Then Data_Element = 'OverdraftTierBandFeeChargeDetail';
		*--- OverdraftFeesCharges ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftFeesCharges' Then Data_Element = 'OverdraftTierBandSetFeesCharges';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-OverdraftTierBand-OverdraftFeesCharges' Then Data_Element = 'OverdraftTierBandFeesCharges';
		*--- Period ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-Period' Then Data_Element = 'CreditIntEligPeriod';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-TradingHistoryEligibility-Period' Then Data_Element = 'TradingHistEligtPeriod';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Period' Then Data_Element = 'FeatureBenEligPeriod';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Period' Then Data_Element = 'FeatureBenGrpEligPeriod';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Period' Then Data_Element = 'FeatureBenefitItemEligPeriod';
		*--- TcsAndCsURL ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CoreProduct-TcsAndCsURL' Then Data_Element = 'CoreProductTcsAndCsURL';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-TcsAndCsURL' Then Data_Element = 'OverdraftTcsAndCsURL';
		*--- Textual ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-Textual' Then Data_Element = 'OtherEligTextual';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-TradingHistoryEligibility-Textual' Then Data_Element = 'TradingHistEligTextual';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Textual' Then Data_Element = 'FeatureBenefitItemTextual';

		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Textual' Then Data_Element = 'FeatureBenItemTextual';
		*--- TierBandMethod ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-TierBandMethod' Then Data_Element = 'CreditIntTierbandSetMethod';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Overdraft-OverdraftTierBandSet-TierBandMethod' Then Data_Element = 'OverdraftTierBandSetMethod';
		*--- Type ---;
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-CreditInterest-TierBandSet-CreditInterestEligibility-Type' Then Data_Element = 'CreditIntEligType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-Eligibility-OtherEligibility-Type' Then Data_Element = 'OtherEligibilityType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-Card-Type' Then Data_Element = 'FeaturesBenCardType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenGrpEligType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenGrpItemEligType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Type' Then Data_Element = 'FeatureBenGrpItemType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Type' Then Data_Element = 'FeatureBenGrpType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenEligType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Type' Then Data_Element = 'FeatureBenItemType';
		If Hierarchy = 'data-Brand-BCA-BCAMarketingState-FeaturesAndBenefits-MobileWallet-Type' Then Data_Element = 'MobileWalletType';
	Count = 1;
Run;

	Proc Summary Data = Work.X_03_nodup Nway Missing;
		Class Data_Element Hierarchy;
		Var Count;
		Output Out = Work.X_04_nodup(Drop = _TYpe_ _Freq_)Sum=;
	Run;
