Hierarchy $300. 
Data_Element $100. 
RowCnt best12. 
Count best12. 
_Record_ID best12. 
_MarkStateID best12. 
_SegmentID best12. 
AER $10. 
Bank $25. 
AgeEligibilityNotes1 $300. 
Agreement $300. 
AgreementLengthMax $10. 
AgreementLengthMin $10. 
AgreementPeriod $10. 
AuthorisedIndicator $5. 
BCAIdentification $20. 
BCAMarketingStateIdentification $15. 
BCAMarketingStateNotes1 $30. 
BCAMarketingStateNotes2 $30. 
BCAMarketingStateNotes3 $300. 
BankGuaranteedIndicator $10. 
BankInterestRate $10. 
BankInterestRateType $10. 
BenefitGroupNominalValue $10. 
BrandBCAName $50. 
BrandName $50. 
BufferAmount $10. 
CalculationMethod $20. 
CardOtherTypeDesc $15. 
ContactlessIndicator $5. 
CoreProductNotes1 $300. 
CoreProductTcsAndCsURL $300. 
CreditCheckEligNotes1 $300. 
CreditIntEligDesc $50. 
CreditIntEligIndicator $5. 
CreditIntEligName $100. 
CreditIntEligOtherTypeDesc $50. 
CreditIntEligOtherTypeName $30. 
CreditIntEligPeriod $10. 
CreditIntEligType $300. 
CreditIntIndentification $50. 
CreditIntTierbandSetMethod $15. 
CreditInterestAmount $10. 
DepositInterestAppliedCoverage $10. 
Destination $15. 
EAR $10. 
EligOtherOfficerTypeCode $10. 
EligibilityAmount $15. 
FeatureBenEligIndicator $5. 
FeatureBenEligNotes1 $500. 
FeatureBenEligPeriod $10. 
FeatureBenEligType $20. 
FeatureBenGrpEligIndicator $50. 
FeatureBenGrpEligName $30. 
FeatureBenGrpEligPeriod $10. 
FeatureBenGrpEligType $20. 
FeatureBenGrpItemEligName $30. 
FeatureBenGrpItemEligType $30. 
FeatureBenGrpItemIndentification $5. 
FeatureBenGrpItemIndicator $5. 
FeatureBenGrpItemName $100. 
FeatureBenGrpItemOtherTypeName $20. 
FeatureBenGrpItemType $15. 
FeatureBenGrpNotes1 $300. 
FeatureBenGrpOtherTypeDesc $100. 
FeatureBenGrpOtherTypeName $30. 
FeatureBenGrpType $30. 
FeatureBenItemEligDesc $100. 
FeatureBenItemEligIndicator $50. 
FeatureBenItemEligName $30. 
FeatureBenItemEligNotes1 $10. 
FeatureBenItemGrpOtherTypeDesc $100. 
FeatureBenItemIndentification $30. 
FeatureBenItemIndicator $300. 
FeatureBenItemName $150. 
FeatureBenItemNotes1 $500. 
FeatureBenItemOtherTypeDesc $300. 
FeatureBenItemTextual $300. 
FeatureBenItemType $30. 
FeatureBenOtherTypeName $50. 
FeatureBenefitEligAmount $10. 
FeatureBenefitGrpAppFreq $30. 
FeatureBenefitGrpCalcFreq $10. 
FeatureBenefitGrpEligDesc $150. 
FeatureBenefitGrpItemAmount $10. 
FeatureBenefitGrpItemEligAmount $10. 
FeatureBenefitGrpName $30. 
FeatureBenefitItemAmount $10. 
FeatureBenefitItemEligAmount $10. 
FeatureBenefitItemEligPeriod $10. 
FeatureBenefitItemOtherTypeCode $10. 
FeatureBenefitItemTextual $300. 
FeaturesBenCardNotes1 $300. 
FeaturesBenCardOtherTypeName $30. 
FeaturesBenCardType $15. 
Fee $10. 
FeeCapOccurrence $10. 
FeeChargeCapFeeType1 $50. 
FeeChargeCapFeeType2 $50. 
FeeChargeCapFeeType3 $50. 
FeeChargeCapMinMaxType $10. 
FeeChargeCapNotes $500. 
FeeChargeCapOtherFeeTypeDesc $30. 
FeeChargeCapOtherFeeTypeName $30. 
FeeChargeCapPeriod $10. 
FeeChargeDetailAppFreq $50. 
FeeChargeDetailCalcFreq $50. 
FeeChargeDetailFeeCategory $30. 
FeeChargeDetailFeeRate $10. 
FeeChargeDetailFeeRateType $30. 
FeeChargeDetailFeeType $50. 
FeeChargeDetailNotes1 $300. 
FeeChargeDetailNotes2 $300. 
FeeChargeDetailOtherFeeTypeDesc $300. 
FeeChargeDetailOtherFeeTypeName $300. 
FeeChargeNegotiableIndicator $5. 
FeeType10 $30. 
FeeType11 $30. 
FeeType12 $30. 
FeeType13 $30. 
FeeType14 $30. 
FeeType15 $30. 
FeeType16 $30. 
FeeType17 $30. 
FeeType18 $30. 
FeeType19 $30. 
FeeType20 $30. 
FeeType21 $30. 
FeeType22 $30. 
FeeType23 $30. 
FeeType24 $30. 
FeeType25 $30. 
FeeType26 $30. 
FeeType27 $30. 
FeeType4 $30. 
FeeType5 $30. 
FeeType6 $30. 
FeeType7 $30. 
FeeType8 $30. 
FeeType9 $30. 
FirstMarketedDate $15. 
FixedVariableInterestRateType $10. 
IDEligNotes1 $300. 
IncludedInMonthlyChargeIndicator $5. 
LastMarketedDate $15. 
LastUpdated $50. 
LegalStructure $20. 
LegalStructureEligNotes1 $100. 
License $100. 
MarketingState $10. 
MaxAmount $10. 
MaxDailyCardWithdrawalLimit $10. 
MaximumAge $10. 
MaximumAmount $10. 
MinAmount $10. 
MinimumAge $10. 
MinimumAmount $10. 
MinimumRate $10. 
MobileWalletNotes1 $300. 
MobileWalletType $15. 
MonthlyCharge $10. 
OfficerEligNotes1 $300. 
OfficerEligOtherOfficerTypeName $20. 
OfficerType $10. 
OtherAppFreqDesc $30. 
OtherCalcFreqDesc $30. 
OtherEligIndicator $5. 
OtherEligName $300. 
OtherEligNotes1 $300. 
OtherEligOtherTypeDesc $50. 
OtherEligOtherTypeName $50. 
OtherEligTextual $50. 
OtherEligibilityDesc $300. 
OtherEligibilityType $20. 
OtherFeeTypeFeeCategory $20. 
OtherFeesChargesAmount $10. 
OtherFeesChargesDetailNotes3 $300. 
OtherFeesChargesFeeCapAmount $10. 
OtherLegalStructureDesc $30. 
OtherLegalStructureName $30. 
OtherOfficerTypeDesc $30. 
OtherSICCodeDesc $10. 
OtherSICCodeName $10. 
OverdraftFeeCapAmount $10. 
OverdraftFeeCapOccurrence $10. 
OverdraftFeeChargeAppFreqDesc $20. 
OverdraftFeeChargeCalcFreqDesc $30. 
OverdraftFeeChargeCapFeeType2 $20. 
OverdraftFeeChargeCapFeeType3 $20. 
OverdraftFeeChargeCapMinMaxType $10. 
OverdraftFeeChargeCapPeriod $10. 
OverdraftFeeChargeDetailAppFreq $20. 
OverdraftFeeChargeDetailCalcFreq $20. 
OverdraftFeeChargeDetailFeeType $30. 
OverdraftFeeChargeDetailNotes2 $20. 
OverdraftFeeChargeNegIndicator $5. 
OverdraftFeeChargeNotes1 $500. 
OverdraftFeeOtherAppFreqName $30. 
OverdraftFeeOtherCalcFreqName $30. 
OverdraftFeesChargesAmount $10. 
OverdraftFeesChargesFeeRate $10. 
OverdraftFeesChargesFeeRateType $10. 
OverdraftFeesChargesFeeType1 $30. 
OverdraftFeesChargesIndicator $5. 
OverdraftIdentification $20. 
OverdraftInterestChargingCove198 $10. 
OverdraftNotes $500. 
OverdraftTcsAndCsURL $300. 
OverdraftTierBandAmount $10. 
OverdraftTierBandFeeRate $10. 
OverdraftTierBandFeeRateType $10. 
OverdraftTierBandFeeType1 $30. 
OverdraftTierBandIdentification $20. 
OverdraftTierbandNotes1 $300. 
OverdraftTierBandSetFeeCapAmount $10. 
OverdraftTierBandSetMethod $30. 
OverdraftTierBandSetNotes1 $300. 
OverdraftTierBandSetNotes2 $500. 
OverdraftTierbandAppFreq $30. 
OverdraftTierbandAppFreqName $20. 
OverdraftTierbandCalcFreq $20. 
OverdraftTierbandCalcFreqName $30. 
OverdraftTierbandCapMinMaxType $20. 
OverdraftTierbandCapPeriod $10. 
OverdraftTierbandFeeType $30. 
OverdraftTierbandIndicator $5. 
OverdraftTierbandNegleIndicator $5. 
OverdraftTierbandNotes2 $50. 
OverdraftType $20. 
PredecessorID $15. 
ProductDescription $300. 
ProductURL $300. 
ResidencyEligNotes1 $50. 
ResidencyIncluded1 $10. 
ResidencyType $20. 
SICCode1 $10. 
SalesAccessChannels1 $30. 
SalesAccessChannels2 $30. 
SalesAccessChannels3 $30. 
SalesAccessChannels4 $30. 
SalesAccessChannels5 $30. 
Scheme1 $20. 
ScoringType $10. 
Segment1 $20. 
Segment2 $20. 
Segment3 $20. 
ServicingAccessChannels1 $20. 
ServicingAccessChannels2 $20. 
ServicingAccessChannels3 $20. 
ServicingAccessChannels4 $20. 
ServicingAccessChannels5 $20. 
ServicingAccessChannels6 $20. 
ServicingAccessChannels7 $20. 
ServicingAccessChannels8 $20. 
ServicingAccessChannels9 $20. 
StateTenureLength $10. 
StateTenurePeriod $10. 
TariffName $20. 
TariffType $20. 
TermsOfUse $100. 
TierBandAppFreq $10. 
TierBandCalcFreq $10. 
TierBandNotes1 $100. 
TierBandSetNotes1 $20. 
TierValueMax $30. 
TierValueMaximum $30. 
TierValueMin $30. 
TierValueMinimum $30. 
TotalResults $10. 
TradingHistEligNotes1 $500. 
TradingHistEligTextual $500. 
TradingHistEligibIndicator $5. 
TradingHistEligibMinMaxType $10. 
TradingHistEligtPeriod $10. 
TradingType $300. 
URL $300. 
Record_Count best12. 

