	Proc Sort Data = Work.X_01(Keep=Hierarchy Data_Element) 
		Out = Work.X_01_Nodup NoDupKey;
		By Hierarchy Data_Element;
	Run;

	Proc Sort Data = Work.X_01_nodup(Keep=Hierarchy Data_Element) 
		Out = Work.X_02_nodup;
		By Data_Element;
	Run;

Data Work.X_03_nodup;
	Set Work.X_02_nodup;
		*--- Amounts ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-Amount' Then Data_Element = 'OtherEligAmount';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-TradingHistoryEligibility-Amount' Then Data_Element = 'TradingHistEligAmount';
		*--- ApplicationFrequency ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-ApplicationFrequency' Then Data_Element = 'LoanIntFeeChargeDetailAppFreq';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-ApplicationFrequency' Then Data_Element = 'LoanIntTierbandAppFreq';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-ApplicationFrequency' Then Data_Element = '';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeDetail-ApplicationFrequency' Then Data_Element = '';
		*--- CalculationFrequency ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-CalculationFrequency' Then Data_Element = 'LoanIntFeesChargesCalcFreq';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-CalculationFrequency' Then Data_Element = 'LoanIntTierbandCalcFreq';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-CalculationFrequency' Then Data_Element = 'OtherFeesChargesCalcFreq';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeDetail-CalculationFrequency' Then Data_Element = 'RepaymentFeeChargeCalcFreq';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-CalculationMethod' Then Data_Element = 'LoanIntTierBandSetCalcMethod';
		*--- Description ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OfficerEligibility-OtherOfficerType-Description' Then Data_Element = 'OfficerEligDesc';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-Description' Then Data_Element = 'OtherEligDesc';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-OtherType-Description' Then Data_Element = 'OtherEligOtherTypeDesc';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-OtherType-Description' Then Data_Element = 'FeatureBenEligDesc';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType-Description' Then Data_Element = 'FeatureBenItemEligDesc';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeCap-OtherFeeType-Description' Then Data_Element = 'OtherFeesChargesCapDesc';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-OtherRepaymentType-Description' Then Data_Element = 'OtherRepaymentTypeDesc';
		*--- FeatureBenefitEligibility ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenGrpEligibility';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenGrpItemEligibility';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenEligibility';
		*--- FeatureBenefitItem ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem' Then Data_Element = 'FeatureBenefitGrpItem';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem' Then Data_Element = 'FeatureBenefitItem';
		*--- FeeAmount ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-FeeAmount' Then Data_Element = 'LoanIntFeeChargeFeeAmount';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-FeeAmount' Then Data_Element = 'OtherFeesChargesFeeAmount';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeDetail-FeeAmount' Then Data_Element = 'RepaymentFeesChargeFeeAmount';
		*--- FeeCapAmount ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeCap-FeeCapAmount' Then Data_Element = 'LoanIntFeesChargesFeeCapAmount';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeCap-FeeCapAmount' Then Data_Element = 'LoanIntTierbandFeeCapAmount';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeCap-FeeCapAmount' Then Data_Element = 'OtherFeesChargesFeeCapAmount';
		If Hierarchy = 'FeeCapAmount' Then Data_Element = '';
		*--- FeeRate ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-FeeRate' Then Data_Element = '';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-FeeRate' Then Data_Element = '';
		*--- FeeRateType ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-FeeRateType' Then Data_Element = 'LoanInterestFeeRateType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-FeeRateType' Then Data_Element = 'OtherFeesChargesFeeRateType';
		*--- FeeType ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeCap-FeeType' Then Data_Element = 'LoanIntFeeChargeCapFeeType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-FeeType' Then Data_Element = 'LoanIntFeeChargeDetaiFeeType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeCap-FeeType' Then Data_Element = 'LoanIntTierbandCapFeeType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-FeeType' Then Data_Element = 'LoanIntTierbandDetailFeeType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeCap-FeeType' Then Data_Element = 'OtherFeesChargesFeeType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-FeeType' Then Data_Element = 'OtherFeesChargesDetailFeeType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeCap-FeeType' Then Data_Element = 'RepaymentFeeChargeCapFeeType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeDetail-FeeType' Then Data_Element = 'RepaymentFeeChargeDetailFeeType';
		*--- FeeType1 ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeCap-FeeType-FeeType1' Then Data_Element = 'LoanIntFeeChargeCapFeeType1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeCap-FeeType-FeeType1' Then Data_Element = 'LoanIntTierbandCapFeeType1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeCap-FeeType-FeeType1' Then Data_Element = 'OtherFeesChargesCapFeeType1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeCap-FeeType-FeeType1' Then Data_Element = 'RepaymentFeeChargeCapFeeType1';
		*--- Identification ---;
		If Hierarchy = 'data-Brand-SMELoan-Identification' Then Data_Element = 'SMELoanIdentification';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Identification' Then Data_Element = 'FeatureBenItemIdentification';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Identification' Then Data_Element = 'MarketingStateIdentification';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-Identification' Then Data_Element = 'LoanIntTierBandSetIdentification';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-Identification' Then Data_Element = 'LoanIntTierBandIdentification';
		*--- Indicator ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-Indicator' Then Data_Element = 'OtherEligIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-TradingHistoryEligibility-Indicator' Then Data_Element = 'TradingHistEligIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenGrpEligIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenGrpItemEligIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Indicator' Then Data_Element = 'FeatureBenGrpItemIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenEligIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Indicator' Then Data_Element = 'FeatureBenItemIndicator';
		*--- LoanInterestFeeChargeCap ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeCap' Then Data_Element = 'LoanIntFeeChargeCap';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeCap' Then Data_Element = 'LoanIntTierBandFeeChargeCap';
		*--- LoanInterestFeeChargeDetail ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail' Then Data_Element = 'LoanIntFeeChargeDetail';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail' Then Data_Element = '';
		*--- LoanInterestFeesCharges ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges' Then Data_Element = 'LoanIntFeesCharges';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges' Then Data_Element = 'LoanIntTierBandFeesCharges';
		*--- MinMaxType ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-TradingHistoryEligibility-MinMaxType' Then Data_Element = 'TradingHistEligMinMaxType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeCap-MinMaxType' Then Data_Element = 'LoanIntFeeChargeCapMinMaxType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeCap-MinMaxType' Then Data_Element = 'LoanIntTiebandMinMaxType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeCap-MinMaxType' Then Data_Element = 'OtherFeesChargesCapMinMaxType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeCap-MinMaxType' Then Data_Element = 'RepaymentFeeChargeCapMinMaxType';
		*--- Name ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-Name' Then Data_Element = 'OtherEligName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-OtherType-Name' Then Data_Element = 'OtherEligOtherTypeName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenGrpEligName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-OtherType-Name' Then Data_Element = 'FeatureBenGrpEligOtherTypeName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenGrpItemEligName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Name' Then Data_Element = 'FeatureBenGrpName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenItemEligName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Name' Then Data_Element = 'FeatureBenItemName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType-Name' Then Data_Element = 'FeatureBenItemOtherTypeName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeCap-OtherFeeType-Name' Then Data_Element = 'FeeChargeCapOtherFeeTypeName';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-OtherRepaymentType-Name' Then Data_Element = 'OtherRepaymentTypeName';
		*--- NegotiableIndicator ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-NegotiableIndicator' Then Data_Element = 'LoanIntFeeChargeNegIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-NegotiableIndicator' Then Data_Element = 'LoanIntTiebandNegIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-NegotiableIndicator' Then Data_Element = 'OtherFeesChargesNegIndicator';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeDetail-NegotiableIndicator' Then Data_Element = 'RepaymentFeeChargeNegIndicator';
		*--- Notes ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-CoreProduct-Notes' Then Data_Element = 'CoreProductNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-AgeEligibility-Notes' Then Data_Element = 'AgeEligibilityNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-CreditCheckEligibility-Notes' Then Data_Element = 'CreditCheckEligNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-IDEligibility-Notes' Then Data_Element = 'IDEligNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-IndustryEligibility-Notes' Then Data_Element = 'IndustryEligNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OfficerEligibility-Notes' Then Data_Element = 'OfficerEligNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-Notes' Then Data_Element = 'OtherEligNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-ResidencyEligibility-Notes' Then Data_Element = 'ResidencyEligNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-TradingHistoryEligibility-Notes' Then Data_Element = 'TradingHistEligNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Notes' Then Data_Element = 'FeatureBenItemNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-Notes' Then Data_Element = 'LoanIntFeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-Notes' Then Data_Element = 'LoanIntFeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-Notes' Then Data_Element = 'LoanIntTierBandNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-Notes' Then Data_Element = 'LoanIntNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-Notes' Then Data_Element = 'FeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-Notes' Then Data_Element = 'RepaymentNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeCap-Notes' Then Data_Element = 'RepaymentFeeChargeCapNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeDetail-Notes' Then Data_Element = 'RepaymentFeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentHoliday-Notes' Then Data_Element = 'RepaymentHolidayNotes';
			*--- Notes1 ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-CoreProduct-Notes-Notes1' Then Data_Element = 'CoreProductNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-AgeEligibility-Notes-Notes1' Then Data_Element = 'AgeEligibilityNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-CreditCheckEligibility-Notes-Notes1' Then Data_Element = 'CreditCheckEligNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-IDEligibility-Notes-Notes1' Then Data_Element = 'IDEligNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-IndustryEligibility-Notes-Notes1' Then Data_Element = 'IndustryEligyNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OfficerEligibility-Notes-Notes1' Then Data_Element = 'OfficerEligNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-ResidencyEligibility-Notes-Notes1' Then Data_Element = 'ResidencyEligNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-TradingHistoryEligibility-Notes-Notes1' Then Data_Element = 'TradingHistEligNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Notes-Notes1' Then Data_Element = 'FeatureBenefitItemNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-Notes-Notes1' Then Data_Element = '';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-LoanInterestFeesCharges-LoanInterestFeeChargeDetail-Notes-Notes1' Then Data_Element = 'LoanIntFeeChargeDetailNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-LoanInterestTierBandSet-LoanInterestTierBand-Notes-Notes1' Then Data_Element = 'LoanIntTierBandNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-LoanInterest-Notes-Notes1' Then Data_Element = 'LoanIntNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-OtherFeesCharges-FeeChargeDetail-Notes-Notes1' Then Data_Element = '';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-Notes-Notes1' Then Data_Element = 'RepaymentNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeCap-Notes-Notes1' Then Data_Element = 'RepaymentFeeChargeCapNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentFeeCharges-RepaymentFeeChargeDetail-Notes-Notes1' Then Data_Element = 'RepaymentFeeChargeDetailNotes1';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Repayment-RepaymentHoliday-Notes-Notes1' Then Data_Element = 'RepaymentHolidayNotes1';
			*--- OtherType ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-OtherType' Then Data_Element = 'OtherEligOtherType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-OtherType' Then Data_Element = 'FeatureBenGrpEligOtherType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType' Then Data_Element = 'FeatureBenItemOtherType';
			*--- Textual ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-Textual' Then Data_Element = 'OtherEligTextual';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-TradingHistoryEligibility-Textual' Then Data_Element = 'TradingHistEligTextual';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Textual' Then Data_Element = 'FeatureBenItemTextual';
			*--- Type ---;
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-Eligibility-OtherEligibility-Type' Then Data_Element = 'OtherEligibilityType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenGrpEligType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Type' Then Data_Element = 'FeatureBenGrpItemType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Type' Then Data_Element = 'FeatureBenGrpType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenItemEligType';
		If Hierarchy = 'data-Brand-SMELoan-SMELoanMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Type' Then Data_Element = 'FeatureBenItemType';
	Count = 1;
Run;

	Proc Summary Data = Work.X_03_nodup Nway Missing;
		Class Data_Element Hierarchy;
		Var Count;
		Output Out = Work.X_04_nodup(Drop = _TYpe_ _Freq_)Sum=;
	Run;
