Hierarchy $250. 
Data_Element $100. 
RowCnt best12. 
Count best12. 
_Record_ID best12. 
_MarkStateID best12. 
_SegmentID best12. 
AgeEligibilityNotes1 $100. 
Bank $25. 
Agreement $300. 
AmountType $20. 
BrandName $30. 
Code $5. 
CoreProductNotes1 $500. 
CreditCheckEligNotes1 $500. 
EarlyPaymentFeeApplicable $5. 
FeatureBenEligDesc $30. 
FeatureBenEligIndicator $5. 
FeatureBenGrpEligIndicator $5. 
FeatureBenGrpEligName $5. 
FeatureBenGrpEligOtherTypeName $30. 
FeatureBenGrpEligType $5. 
FeatureBenGrpItemEligIndicator $5. 
FeatureBenGrpItemEligName $5. 
FeatureBenGrpItemIndicator $5. 
FeatureBenGrpItemType $300. 
FeatureBenGrpName $30. 
FeatureBenGrpType $100. 
FeatureBenItemEligDesc $300. 
FeatureBenItemEligName $5. 
FeatureBenItemEligType $5. 
FeatureBenItemIdentification $10. 
FeatureBenItemIndicator $5. 
FeatureBenItemName $50. 
FeatureBenItemOtherTypeName $50. 
FeatureBenItemTextual $300. 
FeatureBenItemType $25. 
FeatureBenefitItemNotes1 $100. 
FeeCapAmount $10. 
FeeCategory $20. 
FeeChargeCapOtherFeeTypeName $5. 
FirstMarketedDate $10. 
FixedVariableInterestRateType $10. 
FullEarlyRepaymentAllowedIndi36 $30. 
IDEligNotes1 $500. 
IndustryEligyNotes1 $100. 
LastMarketedDate $10. 
LastUpdated $30. 
LegalStructure $30. 
License $100. 
LoanApplicationFeeChargeType $100. 
LoanIntFeeChargeCapFeeType1 $30. 
LoanIntFeeChargeCapMinMaxType $30. 
LoanIntFeeChargeDetailFeeType $30. 
LoanIntFeeChargeDetailAppFreq $20. 
LoanIntFeeChargeDetailNotes1 $300. 
LoanIntFeeChargeFeeAmount $10. 
LoanIntFeeChargeNegIndicator $5. 
LoanIntFeesChargesCalcFreq $20. 
LoanIntFeesChargesFeeCapAmount $10. 
LoanIntNotes1 $500. 
LoanIntTiebandMinMaxType $15. 
LoanIntTiebandNegIndicator $5. 
LoanIntTierBandIdentification $20. 
LoanIntTierBandNotes1 $500. 
LoanIntTierBandSetCalcMethod $20. 
LoanIntTierBandSetIdentification $20. 
LoanIntTierbandAppFreq $20. 
LoanIntTierbandCalcFreq $20. 
LoanIntTierbandCapFeeType1 $20. 
LoanIntTierbandDetailFeeType $20. 
LoanIntTierbandFeeCapAmount $10. 
LoanInterestFeeRateType $10. 
LoanProviderInterestRate $10. 
LoanProviderInterestRateType $10. 
MarketingState $15. 
MarketingStateIdentification $20. 
MaxAmount $10. 
MaxHolidayLength $10. 
MaxHolidayPeriod $10. 
MaxTermPeriod $10. 
MinAmount $10. 
MinTermPeriod $10. 
MinimumAge $10. 
Name $50. 
Notes2 $500. 
Notes3 $500. 
Notes4 $500. 
Notes5 $500. 
OfficerEligDesc $20. 
OfficerEligNotes1 $300. 
OfficerType $100. 
OtherEligAmount $10. 
OtherEligDesc $100. 
OtherEligIndicator $5. 
OtherEligName $50. 
OtherEligOtherTypeDesc $100. 
OtherEligOtherTypeName $50. 
OtherEligTextual $30. 
OtherEligibilityType $30. 
OtherFeesChargesCalcFreq $20. 
OtherFeesChargesCapDesc $100. 
OtherFeesChargesCapFeeType1 $10. 
OtherFeesChargesCapMinMaxType $10. 
OtherFeesChargesDetailFeeType $20. 
OtherFeesChargesFeeAmount $10. 
OtherFeesChargesFeeCapAmount $10. 
OtherFeesChargesFeeRateType $15. 
OtherFeesChargesNegIndicator $5. 
OtherRepaymentTypeDesc $15. 
OtherRepaymentTypeName $30. 
OverPaymentFeeApplicable $5. 
OverpaymentAllowedIndicator $5. 
Period $10. 
PredecessorID $10. 
ProductDescription $500. 
ProductURL $300. 
RepAPR $10. 
RepaymentFeeChargeCalcFreq $20. 
RepaymentFeeChargeCapFeeType1 $20. 
RepaymentFeeChargeCapMinMaxType $20. 
RepaymentFeeChargeCapNotes1 $300. 
RepaymentFeeChargeDetailFeeType $15. 
RepaymentFeeChargeDetailNotes1 $300. 
RepaymentFeeChargeNegIndicator $5. 
RepaymentFeesChargeFeeAmount $10. 
RepaymentFrequency $10. 
RepaymentHolidayNotes1 $300. 
RepaymentNotes1 $300. 
RepaymentType $30. 
ResidencyEligNotes1 $100. 
ResidencyIncluded1 $10. 
ResidencyType $15. 
SMELoanIdentification $20. 
SalesAccessChannels1 $30. 
SalesAccessChannels2 $30. 
SalesAccessChannels3 $30. 
SalesAccessChannels4 $30. 
SalesAccessChannels5 $30. 
ScoringType $10. 
Segment1 $30. 
Segment2 $30. 
ServicingAccessChannels1 $30. 
ServicingAccessChannels2 $30. 
ServicingAccessChannels3 $30. 
ServicingAccessChannels4 $30. 
ServicingAccessChannels5 $30. 
ServicingAccessChannels6 $30. 
ServicingAccessChannels7 $30. 
ServicingAccessChannels8 $30. 
TcsAndCsURL $300. 
TermsOfUse $300. 
TierBandMethod $10. 
TierValueMaxTerm $10. 
TierValueMaximum $10. 
TierValueMinTerm $10. 
TierValueMinimum $10. 
TotalResults $10. 
TradingHistEligAmount $10. 
TradingHistEligIndicator $5. 
TradingHistEligMinMaxType $10. 
TradingHistEligNotes1 $100. 
TradingHistEligTextual $300. 
TradingType $30. 
Type $10. 
URL $300. 
Record_Count best12. 

