Libname OBData "c:\inetpub\wwwroot\sasweb\data\perm"

Hierarchy $250. 
Data_Element $100. 
RowCnt best12. 
Count best12. 
_Record_ID best12. 
_MarkStateID best12. 
_SegmentID best12. 
APR $10. 
Bank $30. 
AgeEligibilityNotes1 $300. 
Agreement $300. 
ApplicationFrequency $20. 
BrandName $50. 
CCCIdentification $30. 
CCCMarketingStateNotes1 $700. 
CCCProductName $100. 
CardScheme1 $20. 
Code $5. 
ContactlessIndicator $5. 
CoreProductNotes1 $300. 
CoreProductNotes2 $300. 
CreditCheckEligNotes1 $300. 
FeatureBenEligAmount $10. 
FeatureBenEligDesc $300. 
FeatureBenGrpCalcFreq $20. 
FeatureBenGrpEligIndicator $5. 
FeatureBenGrpEligName $20. 
FeatureBenGrpEligType $30. 
FeatureBenGrpItemEligIndicator $700. 
FeatureBenGrpItemEligName $30. 
FeatureBenGrpItemEligType $30. 
FeatureBenGrpItemType $30. 
FeatureBenGrpName $30. 
FeatureBenGrpType $30. 
FeatureBenItemEligDesc $100. 
FeatureBenItemEligIndicator $5. 
FeatureBenItemEligName $30. 
FeatureBenItemEligType $30. 
FeatureBenItemIdentification $20. 
FeatureBenItemIndicator $5. 
FeatureBenItemName $100. 
FeatureBenItemNotes1 $300. 
FeatureBenItemOtherTypeDesc $300. 
FeatureBenItemOtherTypeName $100. 
FeatureBenItemTextual $300. 
FeatureBenItemType $20. 
FeatureBentGrpItemIndicator $5. 
FeeCapOccurrence $10. 
FeeChargeCapAmount $10. 
FeeChargeCapCapPeriod $10. 
FeeChargeCapFeeType1 $20. 
FeeChargeCapMinMaxType $10. 
FeeChargeCapNotes1 $20. 
FeeChargeDetailAppFreq $700. 
FeeChargeDetailCalcFreq $10. 
FeeChargeDetailFeeType $10. 
FeeChargeDetailNotes1 $20. 
FeeChargeFeeAmount $30. 
FeeRate $10. 
FirstMarketedDate $10. 
IncludedInPeriodicFeeIndicator $5. 
IndustryEligNotes1 $300. 
LastMarketedDate $10. 
LastUpdated $50. 
LegalStructure $20. 
License $100. 
MarketingState $10. 
MaxAmount $10. 
MaxCreditLimit $10. 
MaxDailyCardWithdrawalLimit $10. 
MaxPurchaseInterestFreeLength63 $10. 
MinAmount $10. 
MinBalanceRepaymentAmount $10. 
MinBalanceRepaymentRate $10. 
MinCreditLimit $10. 
MinimumAge $10. 
MinimumAmount $10. 
NonRepaymentFeeCapMinMaxType $10. 
NonRepaymentFeeCapNotes1 $100. 
NonRepaymentFeeChargeAppFreq $10. 
NonRepaymentFeeChargeCalcFreq $10. 
NonRepaymentFeeChargeCapAmount $10. 
NonRepaymentFeeChargeCapFeeType1 $20. 
NonRepaymentFeeChargeCapPeriod $10. 
NonRepaymentFeeChargeFeeAmount $10. 
NonRepaymentFeeChargeFeeRateType $5. 
NonRepaymentFeeChargeFeeType $20. 
NonRepaymentFeeChargeNotes2 $100. 
NonRepaymentFeeDetailNotes1 $300. 
NonRepaymentNegIndicator $5. 
NonRepaymentOtherAppFreqDesc $20. 
NonRepaymentOtherAppFreqName $20. 
NonRepaymentOtherCalcFreqDesc $20. 
NonRepaymentOtherCalcFreqName $20. 
NonRepaymentOtherFeeCategory $10. 
NonRepaymentOtherFeeTypeDesc $20. 
NonRepaymentOtherFeeTypeName $20. 
Notes3 $700. 
OfficerType $10. 
OtherAppFreqDesc $20. 
OtherAppFreqName $20. 
OtherCalcFreqName $20. 
OtherCalculFreqDesc $20. 
OtherEligDesc $30. 
OtherEligIndicator $50. 
OtherEligName $50. 
OtherEligOtherTypeDesc $50. 
OtherEligOtherTypeName $50. 
OtherEligType $20. 
OtherEligibilityNotes1 $700. 
OtherFeeChargesFeeRateType $5. 
OtherFeeTypeDesc $300. 
OtherFeeTypeFeeCategory $20. 
OtherFeeTypeName $700. 
OtherFeesChargesFeeCategory $50. 
OtherFeesChargesNegIndicator $5. 
OtherFeesChargesNotes2 $300. 
OtherResidencyTypeDesc $30. 
OtherResidencyTypeName $30. 
Period $10. 
PeriodicFee $10. 
PeriodicFeePeriod $10. 
PredecessorID $20. 
ProductDescription $300. 
ProductURL $300. 
RepaymentAllocationNotes1 $300. 
RepaymentAllocationNotes2 $100. 
RepaymentNotes1 $700. 
ResidencyEligNotes1 $300. 
ResidencyIncluded1 $10. 
ResidencyIncluded2 $10. 
ResidencyIncluded3 $10. 
ResidencyIncluded4 $10. 
ResidencyIncluded5 $10. 
ResidencyType $20. 
SalesAccessChannels1 $30. 
SalesAccessChannels2 $30. 
SalesAccessChannels3 $30. 
SalesAccessChannels4 $30. 
SalesAccessChannels5 $30. 
ScoringType $10. 
Segment1 $20. 
ServicingAccessChannels1 $30. 
ServicingAccessChannels2 $30. 
ServicingAccessChannels3 $30. 
ServicingAccessChannels4 $30. 
ServicingAccessChannels5 $30. 
ServicingAccessChannels6 $30. 
ServicingAccessChannels7 $30. 
ServicingAccessChannels8 $30. 
StateTenureLength $10. 
StateTenurePeriod $10. 
TcsAndCsURL $300. 
TermsOfUse $300. 
TotalResults $10. 
TradingHistEligAmount $10. 
TradingHistEligIndicator $5. 
TradingHistEligMinMaxType $10. 
TradingHistEligNotes1 $300. 
TradingHistEligTextual $300. 
TradingType $20. 
URL $300. 
Record_Count best12. 
