	Proc Sort Data = Work.X_01(Keep=Hierarchy Data_Element) 
		Out = Work.X_01_Nodup NoDupKey;
		By Hierarchy Data_Element;
	Run;

	Proc Sort Data = Work.X_01_nodup(Keep=Hierarchy Data_Element) 
		Out = Work.X_02_nodup;
		By Data_Element;
	Run;

Data Work.X_03_nodup;
	Set Work.X_02_nodup;
		*--- Amounts ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-TradingHistoryEligibility-Amount' Then Data_Element = 'TradingHistEligAmount';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Amount' Then Data_Element = 'FeatureBenEligAmount';
		*--- ApplicationFrequency ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-ApplicationFrequency' Then Data_Element = 'FeeChargeDetailAppFreq';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-ApplicationFrequency' Then Data_Element = 'NonRepaymentFeeChargeAppFreq';
		*--- CalculationFrequency ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-CalculationFrequency' Then Data_Element = 'FeatureBenGrpCalcFreq';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-CalculationFrequency' Then Data_Element = 'FeeChargeDetailCalcFreq';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-CalculationFrequency' Then Data_Element = 'NonRepaymentFeeChargeCalcFreq';
		*--- CappingPeriod ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeCap-CappingPeriod' Then Data_Element = 'FeeChargeCapCapPeriod';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeCap-CappingPeriod' Then Data_Element = 'NonRepaymentFeeChargeCapPeriod';
		*--- Description ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-Description' Then Data_Element = 'OtherEligDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-OtherType-Description' Then Data_Element = 'OtherEligOtherTypeDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-ResidencyEligibility-OtherResidencyType-Description' Then Data_Element = 'OtherResidencyTypeDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Description' Then Data_Element = 'FeatureBenEligDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Description' Then Data_Element = 'FeatureBenItemEligDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType-Description' Then Data_Element = 'FeatureBenItemOtherTypeDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherApplicationFrequency-Description' Then Data_Element = 'OtherAppFreqDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherCalculationFrequency-Description' Then Data_Element = 'OtherCalculFreqDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType-Description' Then Data_Element = 'OtherFeeTypeDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherApplicationFrequency-Description' Then Data_Element = 'NonRepaymentOtherAppFreqDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherCalculationFrequency-Description' Then Data_Element = 'NonRepaymentOtherCalcFreqDesc';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherFeeType-Description' Then Data_Element = 'NonRepaymentOtherFeeTypeDesc';
		*--- FeatureBenefitEligibility ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenGrpEligibility';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenGrpItemEligibility';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility' Then Data_Element = 'FeatureBenefitItemEligibility';
		*--- FeatureBenefitItem ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem' Then Data_Element = 'FeatureBenGrpItem';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem' Then Data_Element = 'FeatureBenefitItem';
		*--- FeatureBenefitItem ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-FeeAmount' Then Data_Element = 'FeeChargeFeeAmount';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-FeeAmount' Then Data_Element = 'NonRepaymentFeeChargeFeeAmount';
		*--- FeeCapAmount ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeCap-FeeCapAmount' Then Data_Element = 'FeeChargeCapAmount';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeCap-FeeCapAmount' Then Data_Element = 'NonRepaymentFeeChargeCapAmount';
		*--- FeeCategory ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-FeeCategory' Then Data_Element = 'OtherFeesChargesFeeCategory';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType-FeeCategory' Then Data_Element = 'OtherFeeTypeFeeCategory';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherFeeType-FeeCategory' Then Data_Element = 'NonRepaymentOtherFeeCategory';
		*--- FeeRateType ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-FeeRateType' Then Data_Element = 'OtherFeeChargesFeeRateType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-FeeRateType' Then Data_Element = 'NonRepaymentFeeChargeFeeRateType';
		*--- FeeType ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeCap-FeeType' Then Data_Element = 'FeeChargeCapFeeType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-FeeType' Then Data_Element = 'FeeChargeDetailFeeType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeCap-FeeType' Then Data_Element = 'NonRepaymentFeeChargeCapFeeType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-FeeType' Then Data_Element = 'NonRepaymentFeeChargeFeeType';
		*--- FeeType1 ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeCap-FeeType-FeeType1' Then Data_Element = 'FeeChargeCapFeeType1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeCap-FeeType-FeeType1' Then Data_Element = 'NonRepaymentFeeChargeCapFeeType1';
		*--- Identification ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Identification' Then Data_Element = 'FeatureBenItemIdentification';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Identification' Then Data_Element = 'FeatureBenItemIdentification';
		If Hierarchy = 'data-Brand-CCC-Identification' Then Data_Element = 'CCCIdentification';
		*--- Indicator ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-Indicator' Then Data_Element = 'OtherEligIndicator';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-TradingHistoryEligibility-Indicator' Then Data_Element = 'TradingHistEligIndicator';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenGrpEligIndicator';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenGrpItemEligIndicator';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Indicator' Then Data_Element = 'FeatureBentGrpItemIndicator';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Indicator' Then Data_Element = 'FeatureBenItemEligIndicator';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Indicator' Then Data_Element = 'FeatureBenItemIndicator';
		*--- MinMaxType ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-TradingHistoryEligibility-MinMaxType' Then Data_Element = 'TradingHistEligMinMaxType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeCap-MinMaxType' Then Data_Element = 'FeeChargeCapMinMaxType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeCap-MinMaxType' Then Data_Element = 'NonRepaymentFeeCapMinMaxType';
		*--- Name ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-Name' Then Data_Element = 'OtherEligName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-OtherType-Name' Then Data_Element = 'OtherEligOtherTypeName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-ResidencyEligibility-OtherResidencyType-Name' Then Data_Element = 'OtherResidencyTypeName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenGrpEligName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenGrpItemEligName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Name' Then Data_Element = 'FeatureBenGrpName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Name' Then Data_Element = 'FeatureBenItemEligName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Name' Then Data_Element = 'FeatureBenItemName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType-Name' Then Data_Element = 'FeatureBenItemOtherTypeName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherApplicationFrequency-Name' Then Data_Element = 'OtherAppFreqName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherCalculationFrequency-Name' Then Data_Element = 'OtherCalcFreqName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType-Name' Then Data_Element = 'OtherFeeTypeName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherApplicationFrequency-Name' Then Data_Element = 'NonRepaymentOtherAppFreqNName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherCalculationFrequency-Name' Then Data_Element = 'NonRepaymentOtherCalcFreqNName';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherFeeType-Name' Then Data_Element = 'NonRepaymentOtherFeeTypeName';
		If Hierarchy = 'data-Brand-CCC-Name' Then Data_Element = 'CCCProductName';
		*--- NegotiableIndicator ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-NegotiableIndicator' Then Data_Element = 'OtherFeesChargesNegIndicator';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-NegotiableIndicator' Then Data_Element = 'NonRepaymentNegIndicator';
		*--- Notes ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-CoreProduct-Notes' Then Data_Element = 'CoreProductNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-AgeEligibility-Notes' Then Data_Element = 'AgeEligNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-CreditCheckEligibility-Notes' Then Data_Element = 'CreditCheckEligNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-IndustryEligibility-Notes' Then Data_Element = 'IndustryEligNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-Notes' Then Data_Element = 'OtherEligNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-ResidencyEligibility-Notes' Then Data_Element = 'ResidencyEligNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-TradingHistoryEligibility-Notes' Then Data_Element = 'TradingHistEligNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Notes' Then Data_Element = 'FeatureBenItem-Notes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Notes' Then Data_Element = 'CCCMarketingStateNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeCap-Notes' Then Data_Element = 'FeeChargeCapNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-Notes' Then Data_Element = 'FeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeCap-Notes' Then Data_Element = 'NonRepaymentFeeChargeCapNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-Notes' Then Data_Element = 'NonRepaymentFeeChargeDetailNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-Notes' Then Data_Element = 'RepaymentNotes';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-RepaymentAllocation-Notes' Then Data_Element = 'RepaymentAllocationNotes';
		*--- Notes1 ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-CoreProduct-Notes-Notes1' Then Data_Element = 'CoreProductNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-AgeEligibility-Notes-Notes1' Then Data_Element = 'AgeEligibilityNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-CreditCheckEligibility-Notes-Notes1' Then Data_Element = 'CreditCheckEligNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-IndustryEligibility-Notes-Notes1' Then Data_Element = 'IndustryEligNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-Notes-Notes1' Then Data_Element = 'OtherEligibilityNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-ResidencyEligibility-Notes-Notes1' Then Data_Element = 'ResidencyEligNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-TradingHistoryEligibility-Notes-Notes1' Then Data_Element = 'TradingHistEligNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Notes-Notes1' Then Data_Element = 'FeatureBenItemNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Notes-Notes1' Then Data_Element = 'CCCMarketingStateNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeCap-Notes-Notes1' Then Data_Element = 'FeeChargeCapNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-Notes-Notes1' Then Data_Element = 'FeeChargeDetailNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeCap-Notes-Notes1' Then Data_Element = 'NonRepaymentFeeCapNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-Notes-Notes1' Then Data_Element = 'NonRepaymentFeeDetailNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-Notes-Notes1' Then Data_Element = 'RepaymentNotes1';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-RepaymentAllocation-Notes-Notes1' Then Data_Element = 'RepaymentAllocationNotes1';
		*--- Notes2 ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-CoreProduct-Notes-Notes2' Then Data_Element = 'CoreProductNotes2';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-Notes-Notes2' Then Data_Element = 'OtherFeesChargesNotes2';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-Notes-Notes2' Then Data_Element = 'NonRepaymentFeeChargeNotes2';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-RepaymentAllocation-Notes-Notes2' Then Data_Element = 'RepaymentAllocationNotes2';
		*--- OtherApplicationFrequency ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherApplicationFrequency' Then Data_Element = 'OtherAppFrequency';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherApplicationFrequency' Then Data_Element = 'NonRepaymentOtherAppFrequency';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherCalculationFrequency' Then Data_Element = 'OtherCalcFrequency';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherCalculationFrequency' Then Data_Element = 'NonRepaymentFeeOtherCalcFrequency';
		*--- OtherFeeType ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-OtherFeesCharges-FeeChargeDetail-OtherFeeType' Then Data_Element = 'OtherFeesChargesOtherFeeType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Repayment-NonRepaymentFeeCharges-NonRepaymentFeeChargeDetail-OtherFeeType' Then Data_Element = 'NonRepaymentOtherFeeType';
		*--- OtherType ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-OtherType' Then Data_Element = 'OtherEligOtherType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-OtherType' Then Data_Element = 'FeatureBenItemOtherType';
		*--- Textual ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-TradingHistoryEligibility-Textual' Then Data_Element = 'TradingHistEligTextual';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Textual' Then Data_Element = 'FeatureBenItemTextual';
		*--- Type ---;
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-Eligibility-OtherEligibility-Type' Then Data_Element = 'OtherEligType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenGrpEligType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenGrpItemEligType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-FeatureBenefitItem-Type' Then Data_Element = 'FeatureBenGrpItemType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitGroup-Type' Then Data_Element = 'FeatureBenGrpType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-FeatureBenefitEligibility-Type' Then Data_Element = 'FeatureBenItemEligType';
		If Hierarchy = 'data-Brand-CCC-CCCMarketingState-FeaturesAndBenefits-FeatureBenefitItem-Type' Then Data_Element = 'FeatureBenItemType';
	Count = 1;
Run;

	Proc Summary Data = Work.X_03_nodup Nway Missing;
		Class Data_Element Hierarchy;
		Var Count;
		Output Out = Work.X_04_nodup(Drop = _TYpe_ _Freq_)Sum=;
	Run;
