	Input Hierarchy $250. 
			Data_Element $100. 
			RowCnt best12. 
			Count best12. 
			_Record_ID best12. 
			_MarkStateID best12. 
			_SegmentID best12. 
			Accessibility1 $30. 
			Bank $30. 
			Accessibility2 $30. 
			Accessibility3 $30. 
			Accessibility4 $30. 
			Accessibility5 $30. 
			Accessibility6 $30. 
			Accessibility7 $30. 
			AddressLine1 $50. 
			AddressLine2 $30. 
			AddressLine3 $30. 
			AddressLine4 $30. 
			Agreement $300. 
			BranchName $50. 
			BrandName $50. 
			BuildingNumber $30. 
			Code $5. 
			ContactContent $30. 
			ContactDescription $50. 
			ContactType $30. 
			Country $10. 
			CountrySubDivision1 $50. 
			CustomerSegment1 $20. 
			CustomerSegment2 $20. 
			CustomerSegment3 $20. 
			CustomerSegment4 $20. 
			CustomerSegment5 $20. 
			CustomerSegment6 $20. 
			CustomerSegment7 $20. 
			CustomerSegment8 $20. 
			CustomerSegment9 $20. 
			Identification $30. 
			LastUpdated $30. 
			Latitude $15. 
			License $100. 
			Longitude $15. 
			NonStandardAvailabilityNotes $30. 
			NonStandardClosingTime $20. 
			NonStandardDayName $20. 
			NonStandardDayOpeningTime $20. 
			NonStandardName $20. 
			Note $500. 
			OtherContactTypeDesc $20. 
			OtherContactTypeName $20. 
			OtherServiceFacilityDesc $20. 
			OtherServiceFacilityName $20. 
			Photo $300. 
			PostCode $15. 
			SequenceNumber $10. 
			ServiceAndFacility1 $30. 
			ServiceAndFacility10 $30. 
			ServiceAndFacility11 $30. 
			ServiceAndFacility12 $30. 
			ServiceAndFacility2 $30. 
			ServiceAndFacility3 $30. 
			ServiceAndFacility4 $30. 
			ServiceAndFacility5 $30. 
			ServiceAndFacility6 $30. 
			ServiceAndFacility7 $30. 
			ServiceAndFacility8 $30. 
			ServiceAndFacility9 $30. 
			StandardAvailabilityDayNotes $20. 
			StandardClosingTime $20. 
			StandardDayName $20. 
			StandardDayOpeningTime $20. 
			StartDate $15. 
			StreetName $100. 
			TermsOfUse $100. 
			TotalResults $10. 
			TownName $50. 
			Type $50. 
			Record_Count best12.; 
