set  OBDATA.Pca_geographic1   end=EFIEOD
 Hierarchy $250. 
 Data_Element $100. 
 RowCnt best12. 
 Count best12. 
 _Record_ID best12. 
 _MarkStateID best12. 
 _SegmentID best12. 
 AER $10. 
 Bank $25. 
 AgeEligibilityNotes1 $300. 
 Agreement $300. 
 Amount $10. 
 ApplicationFrequency $15. 
 AuthorisedIndicator $5. 
 BankGuaranteedIndicator $5. 
 BankInterestRateType $10. 
 BenefitGroupNominalValue $10. 
 BrandName $30. 
 BufferAmount $10. 
 CalculationFrequency $15. 
 CalculationMethod $10. 
 CappingPeriod $10. 
 Code $5. 
 ContactlessIndicator $5. 
 CreditIntEligAmount $10. 
 CreditIntEligDesc $100. 
 CreditIntEligName $50. 
 CreditIntEligPeriod $10. 
 CreditInterestEligType $20. 
 DepositInterestAppliedCoverage $10. 
 Description $300. 
 Destination $15. 
 EAR $10. 
 FeatBenefitGroupOtherDesc $20. 
 FeatBenefitItemDesc $100. 
 FeatBenefitItemOtherDesc $10. 
 FeatureBenGroupIdentification $15. 
 FeatureBenItemIdentification $15. 
 FeatureBenefitEligAmount $10. 
 FeatureBenefitEligIndicator $5. 
 FeatureBenefitEligName $30. 
 FeatureBenefitEligOtherName $30. 
 FeatureBenefitEligPeriod $10. 
 FeatureBenefitEligTextual $300. 
 FeatureBenefitEligType $30. 
 FeatureBenefitGrpItemType $30. 
 FeatureBenefitGrpName $50. 
 FeatureBenefitGrpNotes1 $50. 
 FeatureBenefitGrpOtherName $50. 
 FeatureBenefitGrpType $30. 
 FeatureBenefitItemName $300. 
 FeatureBenefitItemNotes1 $300. 
 FeatureBenefitItemNotes2 $300. 
 FeatureBenefitItemNotes3 $300. 
 FeatureBenefitItemTextual $300. 
 FeatureBenefitItemType $50. 
 FeatureBenefitsCardNotes1 $300. 
 FeaturesBenefitsCardType $15. 
 FeeAmount $10. 
 FeeCapAmount $10. 
 FeeCapOccurrence $10. 
 FeeChargeAmount $10. 
 FeeChargeAppFreq $30. 
 FeeChargeCalcFreq $30. 
 FeeChargeCapNotes1 $300. 
 FeeChargeDetailFeeType $50. 
 FeeChargeDetailNotes1 $300. 
 FeeChargeDetailNotes2 $300. 
 FeeChargeDetailNotes3 $300. 
 FeeChargeFeeCategory $15. 
 FeeChargeOtherFeeCategory $15. 
 FeeChargeOtherFeeTypeName $50. 
 FeeChargeOtherTypeDesc $100. 
 FeeMinMaxType $10. 
 FeeRate $10. 
 FeeRateType $20. 
 FeeType $300. 
 FeeType1 $30. 
 FeeType2 $30. 
 FeeType3 $30. 
 FeeType4 $30. 
 FeeType5 $30. 
 FirstMarketedDate $10. 
 FixedVariableInterestRateType $10. 
 IncrementalBorrowingAmount $10. 
 Indicator $5. 
 LastMarketedDate $10. 
 LastUpdated $30. 
 License $300. 
 MarkStateIdentification $15. 
 MarketingState $15. 
 MaximumAge $10. 
 MaximumAmount $10. 
 MinimumAge $10. 
 MinimumAmount $10. 
 MinimumRate $10. 
 MobileWalletNotes1 $500. 
 MobileWalletOtherDesc $100. 
 MobileWalletOtherTypeName $50. 
 MobileWalletType $20. 
 MonthlyMaximumCharge $10. 
 Name $30. 
 Notes $500. 
 Notes1 $300. 
 Notes2 $100. 
 Notes4 $100. 
 OtherEligAmount $10. 
 OtherEligDesc $300. 
 OtherEligIndicator $5. 
 OtherEligName $50. 
 OtherEligType $30. 
 OtherEligibilityNotes1 $300. 
 OverDraftFeeChargeAppFreq $20. 
 OverDraftFeeChargeCalcFreq $15. 
 OverdraftControlIndicator $5. 
 OverdraftFeeChargeAmount $10. 
 OverdraftFeeChargeFeeType $30. 
 OverdraftFeeChargeNotes1 $300. 
 OverdraftIdentification $30. 
 OverdraftInterestChargingCove112 $30. 
 OverdraftTierBandIdentification $30. 
 OverdraftTierBandSetMethod $10. 
 OverdraftType $10. 
 PCAIdentification $20. 
 PCAMarketingStateNotes1 $500. 
 Period $10. 
 PredecessorID $10. 
 ProductDescription $300. 
 ProductName $50. 
 ProductURL $300. 
 ResidencyEligNotes1 $300. 
 ResidencyIncluded1 $10. 
 ResidencyIncluded2 $10. 
 ResidencyIncluded3 $10. 
 ResidencyIncluded4 $10. 
 ResidencyIncluded5 $10. 
 ResidencyIncluded6 $10. 
 ResidencyIncluded7 $10. 
 ResidencyIncluded8 $10. 
 ResidencyType $15. 
 SalesAccessChannels1 $15. 
 SalesAccessChannels2 $15. 
 SalesAccessChannels3 $15. 
 SalesAccessChannels4 $30. 
 Scheme $10. 
 ScoringType $10. 
 Segment1 $15. 
 Segment2 $15. 
 Segment3 $15. 
 ServicingAccessChannels1 $20. 
 ServicingAccessChannels2 $20. 
 ServicingAccessChannels3 $20. 
 ServicingAccessChannels4 $20. 
 ServicingAccessChannels5 $20. 
 ServicingAccessChannels6 $20. 
 ServicingAccessChannels7 $20. 
 ServicingAccessChannels8 $20. 
 ServicingAccessChannels9 $20. 
 StateTenureLength $10. 
 StateTenurePeriod $10. 
 TcsAndCsURL $300. 
 TermsOfUse $300. 
 Textual $300. 
 TierBandIdentification $15. 
 TierBandMethod $10. 
 TierBandSetNotes1 $300. 
 TierValueMax $15. 
 TierValueMaximum $10. 
 TierValueMin $15. 
 TierValueMinimum $10. 
 TotalResults $10. 
 Type $15. 
 URL $300. 
 Record_Count best12. 
